### ISSUE TITLE
Add a donation / support option

### ISSUE THREAD

**Issue by GriffinSauce** [raunofreiberg/ui-playbook#26]
This is such a valuable project, I reference and share it quite often as a quick overview.

I'd love to buy you a coffee!

**Comment by JamesGelok** [comment]
Same!

**Comment by raunofreiberg** [comment]
Wow. Honestly, I'm humbled. 😊

I've set up my profile on buymeacoffee.com. Feel free to show support over at https://www.buymeacoffee.com/rauno

Thanks a lot for the kind words! 🖤

**Comment by GriffinSauce** [comment]
Aw man, I tried several ways but keep getting errors
>  "Authorization failed due to insufficient permissions. Please contact PayPal."

I think your connection from buymeacoffee<->paypal is borked.

Feels kind of ironic to add work this way 😅   anyway; feel free to tag me if you have any other methods or tried fixing that so I can give it another shot! If you'd rather not put energy into that: your work is appreciated and many thanks! 🙏

**Comment by raunofreiberg** [comment]
@GriffinSauce oof.. I fixed it by reconnecting the PayPal integration. Should be fine now. Thanks!

**Comment by GriffinSauce** [comment]
🎉  Works now, cheers!
